name: C/C++ Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            COMPILER: clang
            LINKER: clang
            TARGET: Mac
          - os: windows-latest
            COMPILER: gcc
            LINKER: gcc
            TARGET: Windows
          - os: ubuntu-latest
            COMPILER: cc
            LINKER: cc
            TARGET: Linux
    name: "Building kaiser_${{ matrix.os }}"
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          git submodule init
          git submodule update
          make
      env:
        CC: ${{ matrix.compiler }}
        LD: ${{ matrix.linker }}
